#' Consistent colouring
#'
#' This function returns a vector with colours assigned to each treatment type
#' for consistent colours over the different plots.
#'
#'
#' @param vars A vector of different experimental conditions.
#' @param colourtype One of the RColorBrewer sets. "BW" can be specified if
#' you desire black and white images. this supports up to four vars.
#' Default = "Dark2.
#' @return A named vector with hex type colour codes per levels of "vars".
#' @export
colourpick<-function(vars, colourtype = "Dark2"){

  fac <- factor(vars)
  le <- length(levels(fac))
  if (colourtype == "BW"){
    colsop<- c("#f0f0f0", "#1e1e1e", "#bdbdbd", "#636363")
    cols <- colsop[1:le]
  } else {
    cols <- RColorBrewer::brewer.pal(le, colourtype)
  }
  names(cols) <-levels(fac)
  return(cols)
}


#' ggplot data prep
#'
#' This function creates a unique ID from the cage and mouse id. "Cage: A1 and
#' Mouse ID : L1 will create ID A1L1. it will subsequently melt the data to a
#' long format which can be used by ggplot2.
#'
#'
#' @param data a dataframe with 3 columns of identifiers followed by columns of
#' tumour growth values.
#' @param date indicate if the column names of each tumour growth values
#' are since onset experiment (1-...) or dates (01-01-2020). default = FALSE.
#' @return A named vector with hex type colour codes per levels of "vars".
#' @export
plotdat <- function(data, date=FALSE){
  unID <- mapply(paste,
                 data$Cage,
                 data$`Mouse ID`,
                 USE.NAMES = F)
  unID <- sub(unID, pattern = " ", replacement = "")
  undata <- cbind(unID, data)
  meltgrowth <- data.table::melt(undata, id.vars = c(1:4))
  meltgrowth_use <- meltgrowth[!is.na(meltgrowth$value)]
  meltgrowth_use$value <- as.numeric(meltgrowth_use$value)

# stitch together each string along the columns
  if (date == T) {
  meltgrowth_use$variable <- as.Date(meltgrowth_use$variable,
                                     format = "%Y-%m-%d")
}
  return(meltgrowth_use)
}

#' plot all
#'
#' This function creates a ggplot. It displays the growth of all treatment
#' conditions over time in one graph. It does this by plotting individual
#' measurements and the mean of each treatment as a line with error bars.
#' Colours are assigned by Treatment name as the colourpick function generates.
#'
#'
#' @param data a long format of the tumour growth data as generated by plotdat.
#' @param colours A named vector with hex colours for each treatment variable
#' as generated by colourpick.
#' @param error TRUE/FALSE if error bars should be displayed for each treatment
#' mean. default = TRUE.
#' @param dots TRUE/FALSE if individual measurements should be displayed.
#' default = TRUE.
#' @return A ggplot showing growth of all treatment groups.
#' @export
vivoplot_overall <- function(data, colours, error = T, dots = T) {
  #plot tumour size over time
  plot1 <- ggplot2::ggplot(data, aes(y = value, x = variable)) +
    scale_fill_manual(values=colours)+
    scale_colour_manual(name = "Treatment", values = colours)+
    stat_summary(aes(color = Treatment), fun.y=mean, geom="line") +
    theme(plot.subtitle = element_text(vjust = 1),
          plot.caption = element_text(vjust = 1),
          panel.grid.major = element_line(size = 0.3),
          panel.background = element_rect(fill = "whitesmoke"),
          plot.background = element_rect(fill = "white")) +
    labs(x = NULL, y = "Tumour size (mm3)")
  if (error == T){
   plot1 <- plot1 +
      stat_summary(aes(color = Treatment),
                   fun.data = mean_se, geom = "errorbar")
  }
  if (dots == T){
    plot1 <- plot1 +
      geom_point(aes(colour = Treatment, fill = Treatment),
                 shape=21,
                 size = 2)
  }
  return(plot1)
}
#' plot growth
#'
#' This function creates a ggplot that displays growth of each treatment in a
#' seperate graph. It plots a line displaying the growth over time for each
#' individual animal.
#' Colours are assigned by Treatment name as the colourpick function generates.
#'
#'
#' @param data a long format of the tumour growth data as generated by plotdat.
#' @param colours A named vector with hex colours for each treatment variable
#' as generated by colourpick.
#' @param line TRUE/FALSE If TRUE a line for each animal will be plotted,
#' otherwise dots will indicate each data point per animal. default = TRUE.
#' @return A ggplot of tumour growth per treatment group.
#' @export
vivoplot_treatment <- function(data, colours = colour, line = T) {
  # dots only
  if(line == F){

    treatplot <- ggplot2::ggplot(data = data,
            aes(x = variable,
            y = value,
            color = Treatment,
            group = Treatment)) +
      geom_point(stat = 'identity') +
      theme_minimal() +
      theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
      facet_wrap(~Treatment)+
      scale_fill_manual(values=colours)+
      scale_colour_manual(name = "Treatment", values = colours)+
      labs(x = "days", y = "Tumour size (mm3)")
  }else {
  treatplot <- ggplot2::ggplot(data = data, aes(x = variable,

                                y = value,
                                color = Treatment,
                                group = unID)) +
    # geom_point(stat = 'identity') +
    geom_line(aes(x = as.numeric(variable), y = value)) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    facet_wrap(~Treatment)+
    scale_fill_manual(values=colours)+
    scale_colour_manual(name = "Treatment", values = colours)+
    labs(x = "days", y = "Tumour size (mm3)")
  }
  return(treatplot)
}
#################################################################################
# development
# micemat <- tumcalc(volumes = "~/Documents/car/vol_mice_sheet.csv" )
# frame <- data.table::fread(file= "~/Documents/car/vol_mice_sheet.csv",
#                            select = c(1:3))
# first <- startpick(data = micemat, weight = 90)
# col <- colnames(micemat)
# intervalmatrix <- growthinterval(volumematrix = micemat, datecolumn = col)
# int <- exptime(volumematrix = micemat,datecolumn = col)
# colour <- colourpick(vars = frame$Treatment, colourtype = "Dark2")
# filledmat <- filldate(data = micemat, intervaltime = int)
# matmat <- plotmatrix(filledmatrix = filledmat, startdate = first, intervaltime = int)
# int_dat <- cbind(frame, matmat)
# plot_int_dat<- plotdat(int_dat, date = F)

# vivoplot_treatment(data = plot_int_dat, line = T, colours = colour)
# vivoplot_overall(data = plot_int_dat,error =F ,dots = T, colours = colour)
